# Generated by Django 5.1.7 on 2025-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('none', 'None'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('beauty', 'Beauty')], default='none', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('score', models.SmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('img_path', models.CharField()),
                ('number', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
